### ISSUE TITLE
How to gather rosbag data from Carla Simulator

### ISSUE THREAD

**Issue by Questionboy** [aliekingurgen/ford-autonomous-vehicles-hmi#1]
Hi aliekingurgen:
  I want to know how to gather rosbag data from Carla Simulator. Can you give me some guidances?

**Comment by aliekingurgen** [comment]
Hi!
Rosbag data I used for this example was provided to me, so I am not quite sure about the details of integrating Carla with ROS. Maybe [ros-bridge](https://github.com/carla-simulator/ros-bridge) module of Carla might be helpful...
